version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "CaramelNfts"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cy89ye71d4ar"
s3_prefix = "CaramelNfts"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "InfuraKey=\"8d308c98ca374d39a7148f8fae05a4f6\""
