# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  mintCaramelNft

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  InfuraKey:
    Type: String
  NetworkId:
    Type: String
  PublicKey:
    Type: String
  ApiKeyValue:
    Type: String
  JsonsBucketName:
    Type: String
  ContractAbiBucketName:
    Type: String
  ContractAddress:
    Type: String

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  mintCaramelNftFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/mintCaramelNft.mintCaramelNftHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 900
      Description: A function that receives NFT data and mints an NFT.
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ContractAbiBucket
        - S3CrudPolicy:
            BucketName: !Ref JsonsBucket
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref PrivateKeySecret
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          INFURA_KEY: !Ref InfuraKey
          NETWORK_ID: !Ref NetworkId
          PUBLIC_KEY: !Ref PublicKey
          PRIVATE_KEY_SECRET_NAME: PrivateKeySecret
          JSONS_BUCKET_NAME: !Ref JsonsBucket
          CONTRACT_ABI_BUCKET_NAME: !Ref ContractAbiBucket
          CONTRACT_ADDRESS: !Ref ContractAddress
          SECRETS_MANAGER_ENDPOINT: !Sub 'https://secretsmanager.${AWS::Region}.amazonaws.com' 
          REGION: !Ref AWS::Region
      Events:
        ApiKey:
          Type: Api
          Properties:
            RestApiId: !Ref MintCaramelNftApi
            Path: /
            Method: POST
            Auth:
              ApiKeyRequired: true

  MintCaramelNftApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true # sets for all methods

  PrivateKeySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: PrivateKeySecret
      Description: This secret contains the private key for the account that will sign transactions to the contract
      SecretString: 'ENTER YOUR PRIVATE KEY HERE'

  ApiKey: 
    Type: AWS::ApiGateway::ApiKey
    Properties: 
      Name: !Join ["", [{"Ref": "AWS::StackName"}, "-apikey"]]
      Description: "Mint Caramel NFTs API Key"
      Enabled: true
      GenerateDistinctId: false
      Value: !Ref ApiKeyValue
      StageKeys:
        - RestApiId: !Ref MintCaramelNftApi
          StageName: Prod

  ApiUsagePlan:
    Type: "AWS::ApiGateway::UsagePlan"
    Properties:
      ApiStages: 
        - ApiId: !Ref MintCaramelNftApi
          Stage: Prod     
      Description: !Join [" ", [{"Ref": "AWS::StackName"}, "usage plan"]]
      Quota:
        Limit: 1000
        Period: MONTH
      UsagePlanName: !Join ["", [{"Ref": "AWS::StackName"}, "-usage-plan"]]

  ApiUsagePlanKey:
    Type: "AWS::ApiGateway::UsagePlanKey"
    DependsOn: 
      - MintCaramelNftApi
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan

  JsonsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref JsonsBucketName
      AccessControl: PublicRead
      VersioningConfiguration:
        Status: Enabled
        
  ContractAbiBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref ContractAbiBucketName
      VersioningConfiguration:
        Status: Enabled

  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${MintCaramelNftApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
